#cloud-config

hostname: "coreos"

coreos:
  units:
    - name: open-vm-tools.service
      command: start
      content: |
        [Unit]
        Description=Service for virtual machines hosted on VMware
        Documentation=http://open-vm-tools.sourceforge.net/about.php
        ConditionVirtualization=vmware
        [Service]
        Restart=always
        ExecStart=/usr/bin/rkt run --volume systemd,kind=host,source=/run/systemd --mount volume=systemd,target=/run/systemd --insecure-options=image --net=host docker://godmodelabs/open-vm-tools

    - name: glusterfs.service
      command: start
      content: |
        [Unit]
        Description=Start GlusterFS Docker
        After=docker.service
        [Service]
        Restart=no
        ExecStartPre=/usr/bin/docker pull jsafrane/glusterfs-mounter:latest
        ExecStart=/usr/bin/docker run  --rm --privileged --name cgfs --add-host glusterfs1:10.15.76.231 --add-host glusterfs2:10.15.76.232 --add-host glusterfs3:10.15.76.233 --net=host -v /dev:/dev -v /mnt:/mnt -v /proc:/host/proc -v /run:/run -e HOSTPROCPATH=/host jsafrane/glusterfs-mounter
        ExecStop=-/usr/bin/docker kill cgfs

    - name: mountgfs.service
      command: start
      content: |
        [Unit]
        Description=Mount GlusterFS
        After=glusterfs.service
        Requires=glusterfs.sercice
        [Service]
        Restart=no
        ExecStartPre=/bin/sleep 20
        ExecStart=/usr/bin/docker exec -t cgfs mount -t glusterfs glusterfs1:/volume3 /mnt/volume3
        ExecStop=-/usr/bin/docker exec -t cgfs umount -f /mnt/volume3
